# Generated by Django 6.0.3 on 2026-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_order',
            old_name='endereco_envio',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='estado',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='numero',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
