# Generated by Django 6.0.3 on 2026-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_rename_endereco_envio_pedido_order_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('valor_desconto', models.PositiveIntegerField(help_text='Valor fixo de desconto em R$')),
                ('ativo', models.BooleanField(default=True)),
                ('minimo_pedido', models.PositiveIntegerField(default=0, help_text='Valor mínimo do carrinho para usar')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
