# Generated by Django 6.0.3 on 2026-04-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0005_rename_endereco_completo_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCaminho',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido - 3. Enviado',
                'verbose_name_plural': 'Pedidos - 3. A Caminho',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lojaapp.pedido_order',),
        ),
        migrations.CreateModel(
            name='PedidoFinalizado',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido - 4. Concluído',
                'verbose_name_plural': 'Pedidos - 4. Finalizados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lojaapp.pedido_order',),
        ),
        migrations.CreateModel(
            name='PedidoProcessando',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido - 2. Em Preparo',
                'verbose_name_plural': 'Pedidos - 2. Processando',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lojaapp.pedido_order',),
        ),
        migrations.CreateModel(
            name='PedidoRecebido',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido - 1. Novo',
                'verbose_name_plural': 'Pedidos - 1. Novos (Recebidos)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lojaapp.pedido_order',),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Trabalho', 'Trabalho'), ('Outro', 'Outro')], default='Casa', max_length=20)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('padrao', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_enderecos', to='lojaapp.cliente')),
            ],
        ),
    ]
