# Generated by Django 6.0.3 on 2026-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
