# Generated by Django 6.0.3 on 2026-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0009_produto_preco_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo_fixo_unidade',
            field=models.PositiveIntegerField(default=0, help_text='Custo de embalagem, frete fixo, etc.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imposto_percentual',
            field=models.PositiveIntegerField(default=0, help_text='Ex: 6 para 6%'),
        ),
        migrations.AddField(
            model_name='produto',
            name='taxa_venda_percentual',
            field=models.PositiveIntegerField(default=0, help_text='Taxa cartão/marketplace'),
        ),
    ]
