# Generated by Django 6.0.3 on 2026-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0010_produto_custo_fixo_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_desejada',
            field=models.PositiveIntegerField(default=20, help_text='Quanto você quer ganhar limpo (%)'),
        ),
    ]
