# Generated by Django 6.0.3 on 2026-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0011_produto_margem_desejada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_mercado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='venda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
