# Generated by Django 6.0.3 on 2026-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0013_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='id_transacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cartao', 'Cartão de Crédito'), ('Boleto', 'Boleto Bancário')], default='Pix', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
