# Generated by Django 6.0.3 on 2026-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0014_pedido_order_id_transacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Pedido Cancelado', 'Pedido Cancelado')], default='Pedido Recebido', max_length=50),
        ),
    ]
